---
project_name: devctl

before:
  hooks:
    - go mod tidy

builds:
  - id: devctl
    main: ./cmd/devctl
    binary: devctl
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-X main.version={{.Version}} -X main.gitSha={{.Commit}} -X main.buildDate={{.Date}}"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: nijogeorgep
    name: devctl

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - image_templates:
      - "ghcr.io/nijogeorgep/devctl:{{ .Version }}"
      - "ghcr.io/nijogeorgep/devctl:latest"
    dockerfile: Dockerfile
    goos: linux
    goarch:
      - amd64
      - arm64
    build_flag_templates: "--platform=linux/{{ .Arch }}"
    use: buildx

brews:
  - name: devctl
    tap:
      owner: nijogeorgep
      name: homebrew-devctl
    folder: Formula
    description: "Developer and SRE utility to reduce toil and automate common tasks."
    homepage: "https://github.com/nijogeorgep/devctl"
    install: |
      bin.install "devctl"
    test: |
      system "#{bin}/devctl --help"