project_name: devctl

builds:
  - id: devctl
    main: ./cmd/devctl
    binary: devctl
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-X main.version={{.Version}} -X main.gitSha={{.Commit}} -X main.buildDate={{.Date}}"

dockers:
  - image_templates:
      - "ghcr.io/nijogeorgep/devshell:{{ .Version }}"
      - "ghcr.io/nijogeorgep/devshell:latest"
    dockerfile: Dockerfile
    goos: linux
    goarch:
      - amd64
      - arm64
    build_flag_templates:
      - "--platform=linux/{{ .Arch }}"
    use: buildx

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: nijogeorgep
    name: devctl

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
